// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu2apstQiJteWJ6lMnK2TIWpEIvpp93LU',
    appId: '1:1026089126045:web:2f6f8b65e6012d19fb2c74',
    messagingSenderId: '1026089126045',
    projectId: 'smart-presensee-app',
    authDomain: 'smart-presensee-app.firebaseapp.com',
    storageBucket: 'smart-presensee-app.firebasestorage.app',
    measurementId: 'G-8TEYZ9ZZ5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcucSiIJQmnRkBntvd0s-at8DuksZMcMc',
    appId: '1:1026089126045:android:060e91f22ffdd843fb2c74',
    messagingSenderId: '1026089126045',
    projectId: 'smart-presensee-app',
    storageBucket: 'smart-presensee-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9jhnDpMS4TI27vP-gjHlzpUWqgC2AjJU',
    appId: '1:1026089126045:ios:9f26cb433166ce23fb2c74',
    messagingSenderId: '1026089126045',
    projectId: 'smart-presensee-app',
    storageBucket: 'smart-presensee-app.firebasestorage.app',
    iosBundleId: 'com.matifdeveloper.faceDetector',
  );
}
